"""Measure how much independent information the four JSE indices carry.

The four indices are not four independent samples.  The FTSE/JSE Africa Index
Series ground rules draw all of them from one eligible universe: the All Share
(J203) is that universe, the Top 40 (J200) is its 40 most investable
constituents, and the Resource 10 (J210) and the Financial and Industrial 30
(J213) partition the remainder by ICB industry, the first taking energy and
basic materials and the second excluding them.

Two consequences are structural rather than empirical.  J200 is nested in J203,
so the two must co-move closely.  J210 and J213 are disjoint by construction,
so they are the one genuinely independent contrast in the set.  This script
measures both, on daily log returns and on the log Garman-Klass series that is
the estimand of the report, over the sample the four indices share.

Run:
    PYTHONPATH=src python3 scripts/index_overlap.py \
        --data data --out results/index_overlap.json --tables outputs/tables
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from rvmf.data import clean_ohlc, load_ohlc
from rvmf.rangeproxy import log_proxy

#: Index codes in the order the report tables use.
CODES: tuple[str, ...] = ("J200", "J203", "J210", "J213",
                          "J250", "J258", "J263")

#: Short names, from the FTSE/JSE Africa Index Series ground rules.
NAMES: dict[str, str] = {
    "J200": "Top 40",
    "J203": "All Share",
    "J210": "Resource 10",
    "J213": "Financial and Industrial 30",
    "J250": "Financials and Industrials",
    "J258": "Resources",
    "J263": "Research Affiliates Fundamental All Share",
}


def series(data_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Daily log returns and log Garman-Klass variance, on the common sample.

    Both series come from the cleaned bars, so the contaminated print removed
    from J203 is absent here too and does not inflate a correlation.
    """
    returns: dict[str, pd.Series] = {}
    volatility: dict[str, pd.Series] = {}
    for code in CODES:
        frame, _ = clean_ohlc(load_ohlc(data_dir / f"OHLC_historical_data_{code}.csv"))
        bars = {
            key: np.log(frame[key].to_numpy(dtype=float))
            for key in ("open", "high", "low", "close")
        }
        returns[code] = pd.Series(np.r_[np.nan, np.diff(bars["close"])], index=frame.index)
        volatility[code] = pd.Series(log_proxy(bars, "garman_klass"), index=frame.index)

    r = pd.DataFrame(returns).dropna()
    v = pd.DataFrame(volatility).dropna()
    common = r.index.intersection(v.index)
    return r.loc[common], v.loc[common]


def table_rows(r: pd.DataFrame, v: pd.DataFrame) -> list[str]:
    """Lower-triangle rows: returns above the diagonal, volatility below."""
    cr, cv = r.corr(), v.corr()
    rows = []
    for i, a in enumerate(CODES):
        cells = []
        for j, b in enumerate(CODES):
            if i == j:
                cells.append("")
            elif j > i:
                cells.append(f"{cr.loc[a, b]:.3f}")
            else:
                cells.append(f"{cv.loc[a, b]:.3f}")
        rows.append(f"{a} & " + " & ".join(cells) + r" \\")
    return rows


#: The seven indices resolve into three distinct objects. Membership follows
#: the constituent rules of the ground rules, not the measured correlations.
GROUPS: dict[str, tuple[str, ...]] = {
    "broad": ("J200", "J203", "J263"),
    "resources": ("J210", "J258"),
    "financials and industrials": ("J213", "J250"),
}


def macros(r: pd.DataFrame, v: pd.DataFrame) -> list[str]:
    """Result macros for the prose of Section 4.

    The quantities that matter are within-group and between-group correlation
    of the estimand. Two indices built on the same constituents are close to a
    replication of each other; two built on disjoint constituents are not, and
    only the second kind carries independent cross-sectional evidence.
    """
    cr, cv = r.corr(), v.corr()
    codes = list(CODES)
    group_of = {c: g for g, members in GROUPS.items() for c in members
                if c in codes}
    within = [cv.loc[a, b] for i, a in enumerate(codes) for b in codes[i + 1:]
              if group_of.get(a) == group_of.get(b)]
    between = [cv.loc[a, b] for i, a in enumerate(codes) for b in codes[i + 1:]
               if group_of.get(a) != group_of.get(b)]
    sector = [cv.loc[a, b] for a in GROUPS["resources"]
              for b in GROUPS["financials and industrials"]
              if a in codes and b in codes]
    out = [
        "% Generated by scripts/index_overlap.py -- do not edit by hand.",
        rf"\newcommand{{\ovN}}{{{len(r):,}}}".replace(",", "{,}"),
        rf"\newcommand{{\ovFirst}}{{{r.index[0].date()}}}",
        rf"\newcommand{{\ovLast}}{{{r.index[-1].date()}}}",
        rf"\newcommand{{\ovGroups}}{{{len(GROUPS)}}}",
        rf"\newcommand{{\ovIndices}}{{{len(codes)}}}",
    ]
    if within:
        out += [rf"\newcommand{{\ovWithinLo}}{{{min(within):.3f}}}",
                rf"\newcommand{{\ovWithinHi}}{{{max(within):.3f}}}"]
    if between:
        out += [rf"\newcommand{{\ovBetweenLo}}{{{min(between):.3f}}}",
                rf"\newcommand{{\ovBetweenHi}}{{{max(between):.3f}}}"]
    if sector:
        out += [rf"\newcommand{{\ovSectorLo}}{{{min(sector):.3f}}}",
                rf"\newcommand{{\ovSectorHi}}{{{max(sector):.3f}}}"]
    for key, pair in (("Res", ("J210", "J258")), ("Fin", ("J213", "J250")),
                      ("Broad", ("J200", "J203"))):
        if pair[0] in codes and pair[1] in codes:
            out += [rf"\newcommand{{\ovTwin{key}}}{{{cv.loc[pair]:.3f}}}",
                    rf"\newcommand{{\ovTwin{key}Ret}}{{{cr.loc[pair]:.3f}}}"]
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", default="data")
    ap.add_argument("--codes", nargs="*", default=list(CODES))
    ap.add_argument("--out", default="results/index_overlap.json")
    ap.add_argument("--tables", default="outputs/tables")
    args = ap.parse_args()

    globals()["CODES"] = tuple(args.codes)
    r, v = series(Path(args.data))
    print(f"common sample: {len(r)} days, {r.index[0].date()} to {r.index[-1].date()}")
    print("returns\n", r.corr().round(3))
    print("log Garman-Klass\n", v.corr().round(3))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        "codes": list(CODES),
        "names": NAMES,
        "n": int(len(r)),
        "first": str(r.index[0].date()),
        "last": str(r.index[-1].date()),
        "corr_returns": r.corr().round(4).to_dict(),
        "corr_log_garman_klass": v.corr().round(4).to_dict(),
    }, indent=2) + "\n")
    print(f"  wrote {out}")

    tables = Path(args.tables)
    tables.mkdir(parents=True, exist_ok=True)
    if tables.is_dir():
        (tables / "index_overlap.tex").write_text("\n".join(table_rows(r, v)) + "\n")
        (tables / "macros_overlap.tex").write_text("\n".join(macros(r, v)) + "\n")
        print(f"  wrote {tables/'index_overlap.tex'} and macros_overlap.tex")


if __name__ == "__main__":
    main()
