#!/usr/bin/env python3
"""Table, macros and figure for the sub-period analysis of RQ5.

Run:
    PYTHONPATH=src python3 scripts/make_subperiod_outputs.py
"""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

COLOUR_LAMBDA = "#4C78C8"
COLOUR_H = "#0A7B3E"
COLOUR_REJECT = "#A6372B"

#: Periods of market stress the sample spans, for annotation only. The blocks
#: are laid down mechanically and take no account of these dates.
EPISODES: tuple[tuple[str, str], ...] = (
    ("2008-09-01", "2009-06-30"),   # global financial crisis
    ("2015-08-01", "2016-06-30"),   # commodity collapse and domestic stress
    ("2020-02-01", "2021-03-31"),   # pandemic
    ("2022-02-01", "2022-12-31"),   # invasion of Ukraine
)


def _d(s: str) -> date:
    y, m, dd = (int(x) for x in s.split("-"))
    return date(y, m, dd)


def _listed(names) -> str:
    """Join names the way prose does: a, b and c."""
    names = list(names)
    if len(names) < 2:
        return "".join(names)
    return ", ".join(names[:-1]) + " and " + names[-1]


def _write(path: Path, text: str) -> None:
    path.write_text(text)
    print(f"  wrote {path}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", default="results_v2/subperiods.json")
    ap.add_argument("--out", default="outputs")
    args = ap.parse_args()

    d = json.loads(Path(args.results).read_text())
    codes = list(d["indices"])
    out = Path(args.out)
    tables, figures = out / "tables", out / "figures"
    tables.mkdir(parents=True, exist_ok=True)
    figures.mkdir(parents=True, exist_ok=True)

    # ---- tables ---------------------------------------------------------
    # One table per parameter. The two carry different block lengths and
    # different tests, and a single table of them does not fit the page.
    lam_rows, h_rows = [], []
    for code in codes:
        e = d["indices"][code]
        lam = [b["lambda_sq"] for b in e["lambda_blocks"]]
        hs = [b["H"] for b in e["H_blocks"]]
        rej = sum(b["p_value"] < 0.05 for b in e["lambda_blocks"])
        ld, hd, st = (e["lambda_dispersion"], e["H_dispersion"],
                      e["stress_contrast"])
        lam_rows.append(
            f"{code} & {len(lam)} & {min(lam):.3f}--{max(lam):.3f} & "
            f"{rej}/{len(lam)} & {ld['observed_sd']:.4f} & "
            f"{ld['null_sd_q95']:.4f} & {ld['p_value']:.3f} & "
            f"{st['difference']:+.4f} & {st['p_value']:.2f} \\\\")
        h_rows.append(
            f"{code} & {len(hs)} & {min(hs):.3f}--{max(hs):.3f} & "
            f"{hd['observed_sd']:.3f} & {hd['null_sd_q95']:.3f} & "
            f"{hd['p_value']:.3f} \\\\")
    _write(tables / "subperiods_lambda.tex", "\n".join(lam_rows) + "\n")
    _write(tables / "subperiods_H.tex", "\n".join(h_rows) + "\n")

    # ---- macros ---------------------------------------------------------
    lam_p = {c: d["indices"][c]["lambda_dispersion"]["p_value"] for c in codes}
    sc = {c: d["indices"][c]["stress_contrast"] for c in codes}
    H_p = {c: d["indices"][c]["H_dispersion"]["p_value"] for c in codes}
    moving = sorted(c for c in codes if lam_p[c] < 0.05)
    all_lam = [b["lambda_sq"] for c in codes for b in d["indices"][c]["lambda_blocks"]]
    all_rej = sum(b["p_value"] < 0.05 for c in codes
                  for b in d["indices"][c]["lambda_blocks"])
    n_blocks = len(all_lam)
    macros = [
        "% Generated by scripts/make_subperiod_outputs.py -- do not edit by hand.",
        rf"\newcommand{{\spShort}}{{{d['short']}}}",
        rf"\newcommand{{\spLong}}{{{d['long']:,}}}".replace(",", "{,}"),
        rf"\newcommand{{\spBlocks}}{{{n_blocks}}}",
        rf"\newcommand{{\spRejecting}}{{{all_rej}}}",
        rf"\newcommand{{\spLamLo}}{{{min(all_lam):.3f}}}",
        rf"\newcommand{{\spLamHi}}{{{max(all_lam):.3f}}}",
        rf"\newcommand{{\spMoving}}{{{len(moving)}}}",
        rf"\newcommand{{\spMovingNames}}{{{_listed(moving)}}}",
        rf"\newcommand{{\spStillNames}}{{{_listed([c for c in codes if c not in moving])}}}",
        rf"\newcommand{{\spStill}}{{{len(codes) - len(moving)}}}",
        rf"\newcommand{{\spIndices}}{{{len(codes)}}}",
        rf"\newcommand{{\spLamPMin}}{{{min(lam_p.values()):.3f}}}",
        rf"\newcommand{{\spLamPMax}}{{{max(lam_p.values()):.3f}}}",
        rf"\newcommand{{\spHPMin}}{{{min(H_p.values()):.3f}}}",
        rf"\newcommand{{\spHNullSdLo}}{{{min(d['indices'][c]['H_dispersion']['null_sd_median'] for c in codes):.3f}}}",
        rf"\newcommand{{\spHNullSdHi}}{{{max(d['indices'][c]['H_dispersion']['null_sd_median'] for c in codes):.3f}}}",
        rf"\newcommand{{\spHBlocksMax}}{{{max(len(d['indices'][c]['H_blocks']) for c in codes)}}}",
        rf"\newcommand{{\spSets}}{{{d['indices'][codes[0]]['lambda_dispersion']['sets']}}}",
        rf"\newcommand{{\spReps}}{{{d['reps']}}}",
        rf"\newcommand{{\spStressPMin}}{{{min(sc[c]['p_value'] for c in codes):.2f}}}",
        rf"\newcommand{{\spStressPMax}}{{{max(sc[c]['p_value'] for c in codes):.2f}}}",
        rf"\newcommand{{\spStressBlocksLo}}{{{min(sc[c]['stress_blocks'] for c in codes)}}}",
        rf"\newcommand{{\spStressBlocksHi}}{{{max(sc[c]['stress_blocks'] for c in codes)}}}",
        rf"\newcommand{{\spStressLower}}{{{sum(sc[c]['difference'] < 0 for c in codes)}}}",
        # Reported as a magnitude, because the direction is stated in words and
        # a signed range reads backwards when every sign is the same.
        rf"\newcommand{{\spStressGapLo}}{{{min(abs(sc[c]['difference']) for c in codes):.4f}}}",
        rf"\newcommand{{\spStressGapHi}}{{{max(abs(sc[c]['difference']) for c in codes):.4f}}}",
        rf"\newcommand{{\spStressDraws}}{{{sc[codes[0]]['draws']:,}}}".replace(",", "{,}"),
    ]
    _write(tables / "macros_subperiods.tex", "\n".join(macros) + "\n")

    # ---- figure: small multiples of the intermittency ---------------------
    # Only the intermittency is plotted. The roughness shows no movement on any
    # index and its blocks number at most five, so it is carried by the table
    # rather than by seven near-empty panels. Each estimate is drawn across the
    # block it comes from, not as a point at the block's end, so a block reads
    # against the episode it covers. The blocks are laid down mechanically; the
    # shading is annotation added afterwards.
    plt.rcParams.update({"axes.titlesize": 9, "axes.labelsize": 8,
                         "xtick.labelsize": 7, "ytick.labelsize": 7})
    ncol = 4
    nrow = -(-len(codes) // ncol)
    fig, axes = plt.subplots(nrow, ncol, figsize=(7.6, 2.0 * nrow + 0.7),
                             sharey=True)
    flat = axes.ravel()
    lam_max = max(all_lam) * 1.12

    for j, code in enumerate(codes):
        a = flat[j]
        e = d["indices"][code]
        first = _d(e["lambda_blocks"][0]["start"])
        last = _d(e["lambda_blocks"][-1]["end"])
        drawn = False
        for lo, hi in EPISODES:
            lo_d, hi_d = max(_d(lo), first), min(_d(hi), last)
            if lo_d >= hi_d:
                continue
            a.axvspan(lo_d, hi_d, color="#9A9A9A", alpha=0.20, lw=0,
                      label="market stress" if not drawn else None)
            drawn = True

        first_ok = first_no = True
        for b in e["lambda_blocks"]:
            rejects = b["p_value"] < 0.05
            label = None
            if rejects and first_ok:
                label, first_ok = "rejects monofractality", False
            elif not rejects and first_no:
                label, first_no = "does not reject", False
            a.hlines(b["lambda_sq"], _d(b["start"]), _d(b["end"]), lw=2.4,
                     color=COLOUR_LAMBDA if rejects else COLOUR_REJECT,
                     zorder=3, label=label)
        a.set_ylim(0, lam_max)
        a.set_title(code)
        a.tick_params(axis="x", rotation=45)
        if j % ncol == 0:
            a.set_ylabel(r"$\hat\lambda^2$ per " + f"{d['short']} days")

    for a in flat[len(codes):]:
        a.axis("off")
    for a in flat[:len(codes)]:
        a.grid(True, axis="y", lw=0.4, color="#D8D8D8")
        a.set_axisbelow(True)
        for side in ("top", "right"):
            a.spines[side].set_visible(False)

    handles, labels = [], []
    for a in flat[:len(codes)]:
        h, l = a.get_legend_handles_labels()
        for hi, li in zip(h, l):
            if li not in labels:
                handles.append(hi); labels.append(li)
    fig.legend(handles, labels, frameon=False, fontsize=7.5, ncol=3,
               loc="lower center", bbox_to_anchor=(0.5, -0.01))
    fig.tight_layout(rect=(0, 0.06, 1, 1))
    fig.savefig(figures / "fig_subperiods.png", dpi=200)
    plt.close(fig)
    print(f"  wrote {figures / 'fig_subperiods.png'}")


if __name__ == "__main__":
    main()
