#!/usr/bin/env python3
"""Table, macros and figure for the identification frontier in window length.

Reads the two sweeps and writes the report artefacts, so the numbers in the
text cannot drift from the runs that produced them.

Run:
    PYTHONPATH=src python3 scripts/make_power_outputs.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

#: House series colours. The moment estimator is the blue of Figure 2 and the
#: learned estimator the green, re-stepped to clear the chroma floor at which a
#: green reads as grey.
COLOUR_MOMENTS = "#4C78C8"
COLOUR_LEARNED = "#0A7B3E"

#: The span of a crisis episode in trading days, from the shortest of the four
#: episodes the sample covers to the longest.
CRISIS_LO, CRISIS_HI = 220, 490


def _length_axis(a) -> None:
    """Label every length actually sampled, so no point sits unlabelled."""
    a.set_xscale("log")
    a.set_xticks([250, 500, 1000, 2000, 3500, 5100])
    a.get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
    a.tick_params(axis="x", labelsize=7.5)
    a.minorticks_off()


def _write(path: Path, text: str) -> None:
    path.write_text(text)
    print(f"  wrote {path}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", default="results_v2/power_study")
    ap.add_argument("--out", default="outputs")
    args = ap.parse_args()

    res = Path(args.results)
    out = Path(args.out)
    tables, figures = out / "tables", out / "figures"
    tables.mkdir(parents=True, exist_ok=True)
    figures.mkdir(parents=True, exist_ok=True)

    meta = json.loads((res / "frontier.json").read_text())
    frontier = meta["rows"]
    reps, n_train = meta["reps"], meta["n_train"]
    cells = frontier[0]["net_cells"] // 5          # cells at H = 0.10
    frontier.sort(key=lambda r: r["length"])
    power = {r["length"]: r for r in
             json.loads((res / "power_lambda.json").read_text())["rows"]}

    # ---- table ----------------------------------------------------------
    rows = []
    for r in frontier:
        L = r["length"]
        p = power.get(L)
        weakest = p["power"]["0.017"]["power"] if p else None
        rows.append(
            f"{L:,}".replace(",", "{,}")
            + f" & {r['net_H_rmse_at_0.10']:.3f} & {r['gmm_H_rmse_at_0.10']:.3f}"
            + f" & {r['net_lambda_rel']:.2f}"
            + (f" & {p['critical_value']:.4f} & {weakest:.2f}" if p else " & --- & ---")
            + r" \\")
    _write(tables / "frontier.tex", "\n".join(rows) + "\n")

    # ---- macros ---------------------------------------------------------
    met = [r for r in frontier if r["net_H_rmse_at_0.10"] < 0.05]
    missed = [r for r in frontier if r["net_H_rmse_at_0.10"] >= 0.05]
    first_met = min(r["length"] for r in met)
    last_missed = max(r["length"] for r in missed if r["length"] < first_met)
    floor = min(r["net_H_rmse_at_0.10"] for r in frontier)
    gmm_best = min(r["gmm_H_rmse_at_0.10"] for r in frontier)
    weakest_250 = power[250]["power"]["0.017"]["power"]

    macros = [
        "% Generated by scripts/make_power_outputs.py -- do not edit by hand.",
        rf"\newcommand{{\pwMet}}{{{first_met:,}}}".replace(",", "{,}"),
        rf"\newcommand{{\pwMissed}}{{{last_missed:,}}}".replace(",", "{,}"),
        rf"\newcommand{{\pwFloor}}{{{floor:.3f}}}",
        rf"\newcommand{{\pwGmmBest}}{{{gmm_best:.3f}}}",
        rf"\newcommand{{\pwShortest}}{{{min(r['length'] for r in frontier)}}}",
        rf"\newcommand{{\pwShortestRmse}}{{{frontier[0]['net_H_rmse_at_0.10']:.3f}}}",
        rf"\newcommand{{\pwCrisisLo}}{{{CRISIS_LO}}}",
        rf"\newcommand{{\pwCrisisHi}}{{{CRISIS_HI}}}",
        rf"\newcommand{{\pwPowerShortest}}{{{weakest_250:.2f}}}",
        rf"\newcommand{{\pwCritShortest}}{{{power[250]['critical_value']:.4f}}}",
        rf"\newcommand{{\pwCritLongest}}{{{power[max(power)]['critical_value']:.4f}}}",
        # Replicate noise on a pooled figure: for a mean of squares over
        # ``reps`` draws in each of ``cells`` cells, the standard error of the
        # root mean squared error is about rmse / sqrt(2 * reps * cells). Two
        # figures closer than this are not distinguishable.
        rf"\newcommand{{\pwSe}}{{{0.05 / np.sqrt(2 * reps * cells):.4f}}}",
        rf"\newcommand{{\pwNtrain}}{{{n_train:,}}}".replace(",", "{,}"),
        rf"\newcommand{{\pwLengths}}{{{len(frontier)}}}",
        rf"\newcommand{{\pwNullReps}}{{{power[250]['null_reps']}}}",
        rf"\newcommand{{\pwAltReps}}{{{power[250]['alt_reps']}}}",
    ]
    _write(tables / "macros_frontier.tex", "\n".join(macros) + "\n")

    # ---- figure ---------------------------------------------------------
    L = np.array([r["length"] for r in frontier], dtype=float)
    # Sized so that the figure is reduced only slightly at text width: a wide
    # figure scaled to fit renders its labels below legible size on the page.
    plt.rcParams.update({
        "axes.titlesize": 9.5, "axes.labelsize": 9,
        "xtick.labelsize": 8, "ytick.labelsize": 8,
    })
    fig, ax = plt.subplots(1, 2, figsize=(7.4, 3.6))

    # Left: error in H against window length, both estimators, one y axis.
    ax[0].axvspan(CRISIS_LO, CRISIS_HI, color="#B0B0B0", alpha=0.22, lw=0,
                  label="span of a crisis episode")
    ax[0].plot(L, [r["gmm_H_rmse_at_0.10"] for r in frontier], marker="o", ms=5,
               lw=2.0, color=COLOUR_MOMENTS, label="moment estimator")
    ax[0].plot(L, [r["net_H_rmse_at_0.10"] for r in frontier], marker="s", ms=5,
               lw=2.0, color=COLOUR_LEARNED, label="learned estimator")
    ax[0].axhline(0.05, color="k", ls="--", lw=0.9, label="threshold 0.05")
    ax[0].set_xscale("log")
    _length_axis(ax[0])
    ax[0].set_xlabel("window length (trading days)")
    ax[0].set_ylabel(r"error of $\hat H$ at $H=0.1$ (RMSE)")
    ax[0].set_title("How short a window still measures roughness")

    # Right: what the test of monofractality has to clear, against what the
    # indices carry. A power curve would be three flat lines at one.
    crit = [power[int(x)]["critical_value"] for x in L if int(x) in power]
    xs = [x for x in L if int(x) in power]
    ax[1].axhspan(0.017, 0.047, color=COLOUR_LEARNED, alpha=0.16, lw=0,
                  label="intermittency the indices carry")
    ax[1].plot(xs, crit, marker="o", ms=5, lw=2.0, color=COLOUR_MOMENTS,
               label="95th percentile of the monofractal null")
    ax[1].set_xscale("log")
    _length_axis(ax[1])
    ax[1].set_ylim(0.0, 0.055)
    ax[1].set_xlabel("window length (trading days)")
    ax[1].set_ylabel(r"$\hat\lambda^2$")
    ax[1].set_title("What the test of monofractality has to clear")

    for a in ax:
        a.grid(True, which="major", axis="y", lw=0.4, color="#D8D8D8")
        a.set_axisbelow(True)
        for side in ("top", "right"):
            a.spines[side].set_visible(False)
        a.legend(frameon=False, fontsize=7, loc="upper center",
                 bbox_to_anchor=(0.5, -0.24), ncol=1, handlelength=1.6,
                 columnspacing=1.2)
    fig.tight_layout()
    fig.savefig(figures / "fig_frontier.png", dpi=200)
    plt.close(fig)
    print(f"  wrote {figures / 'fig_frontier.png'}")


if __name__ == "__main__":
    main()
